version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=exchange
    volumes: 
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  exchange:
    restart: always
    build:
      context: ./
      dockerfile: ./exchange/Dockerfile
    volumes:
      - /app/node_modules
      - /app/build
    command: npm run start

  users:
    restart: always
    build:
      context: ./
      dockerfile: ./users/Dockerfile
    depends_on:
      - db
      - exchange
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: my_user
      DB_PASSWORD: root
      DB_NAME: exchange
      EXCHANGE_HOST: exchange
    volumes:
      - /app/node_modules
      - /app/build
    command: npm run start
  
  api:
    restart: always
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    depends_on:
      - users
    ports:
      - 80:80
    environment:
      USERS_HOST: users
    volumes:
      - /app/node_modules
      - /app/build
    command: npm run start