version: '3.8'

services:
  frontend:
    restart: always
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/openAPI
      - /app/.next
    command: npm run start
